### ISSUE TITLE
Docs suggestion - Remove card hover movement effect

### ISSUE THREAD

**Issue by simshaun** [ganapativs/bttn.css#3]
Again, just a suggestion (based on my personal opinion)...

Browsing the button effects on https://bttn.surge.sh/, the card hover effect is quite jarring. The card moving when I'm trying to throw my cursor to the button is what's throwing me off I think.

**Comment by ganapativs** [comment]
Yup, Actually makes sense. Updated https://bttn.surge.sh/. Thanks for the feedback.

**Comment by simshaun** [comment]
That's much better! Thanks
