### ISSUE TITLE
Bower support?

### ISSUE THREAD

**Issue by fahrenq** [ganapativs/bttn.css#4]
Hello, I really like your project, but don't see bower support? 

It's very important for a bunch of non nodejs developers (but is there even npm support?).

It would be great if you add the package to bower. 

Thanks.

**Comment by ganapativs** [comment]
Cool, I'll try to add it to bower and npm asap.

**Comment by vinayakkulkarni** [comment]
any updates on this?
> bower support

**Comment by ganapativs** [comment]
Was little busy with work, I'll add bower and npm support by tomorrow.

**Comment by dbarabashh** [comment]
Hi everyone. You can try to install the package using bower **bower install bttn.css**. 
I did it for us
@ganapativs

**Comment by ganapativs** [comment]
Sorry, didn't get free time to do it. Thanks @dbarabashdev.

**Comment by dbarabashh** [comment]
@ganapativs all is good, it's easily

**Comment by ganapativs** [comment]
Added to README. Closing the issue.
