### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by YvonneD** [ganapativs/bttn.css#5]
Here I have some questions:
1.How can I change the style of button tag?Why soesn't work when I style button?
2.What's the meaning of i tag with class?like  `<i class="icon-menu"></i>`Is there any other class attributes?
3.How can I set the margin and padding of the button?
Thanks

**Comment by ganapativs** [comment]
1) You can use `bttn` classes provided in bttn.css, you can add your own CSS class after requiring bttn.css to override styles.

2) No icon classes are provided by default. You can use your own icon library.

3) Again, You can add your own CSS class after requiring bttn.css to override styles.
